### ISSUE TITLE
Track Current Issues

### ISSUE THREAD

**Issue by weaponmasterjax** [weaponmasterjax/device_xiaomi_everpal#1]
- [x] fastcharge
- [x] headphone jack output too loud
- [x] selinux is permissive
- [x] fingerprint in power button buggy
- [x] bt disconnects
- [x] GNSS FOSSlize
- [x] seperate vendor kernel modules and move kernel out tree

**Comment by weaponmasterjax** [comment]
For fingerprint: switch to aidl fp hal

**Comment by SteveZMTstudios** [comment]
- [ ] fix screen lock still lighting
- [ ] fix light setting not work
PLZ!  orz

**Comment by weaponmasterjax** [comment]
> 

Didn't find the bugs you described.

**Comment by weaponmasterjax** [comment]
> For fingerprint: switch to aidl fp hal

No need now since the bug has nothing to do with fp hal.
The root cause is the fp driver of goodix always sends a click signal after fp scanner being triggered by finger.
Fixed with https://github.com/weaponmasterjax/device_xiaomi_everpal/commit/966f968d83baf4112d9000655757eaf17f6c943f
and https://github.com/weaponmasterjax/device_xiaomi_everpal/commit/1922ff56a7a4b15bbdccd21b803a2c86d9d14d77
