### ISSUE TITLE
Remove Android auto app.

### ISSUE THREAD

**Issue by ANIL80531** [weaponmasterjax/device_xiaomi_everpal#2]
I don't own a car please remove Android auto app from rom anyone can download this app from play store if needed. It became a bloatware for me using 61mb of space.

**Comment by weaponmasterjax** [comment]
@ANIL80531 It's a mandatory component for Android as A LOT of people needed it to connect with their automobiles and we SHOULDN'T remove it.

**Comment by weaponmasterjax** [comment]
If you insist on removing it then do it on your own device.

**Comment by ANIL80531** [comment]
It is a system app in ROM how can I remove it. People can download it from play store it's not a pixel device specific app. It's a bloatware for me.

**Comment by weaponmasterjax** [comment]
@ANIL80531 Can't you just google for a magisk way?

**Comment by ANIL80531** [comment]
I can't use magisk, my SBI banking app detects root even with magisk hide. Anyway the app will still be there in ROM cause it's read only memory after a simple reset I will get it back.

**Comment by riconghost** [comment]
@ANIL80531 @ANIL80531 use safetynet fix
