### ISSUE TITLE
Cannot start after installed magisk 26.3 in evolutionX latest version(7.9.9 RC1)

### ISSUE THREAD

**Issue by chen2021-web** [weaponmasterjax/device_xiaomi_everpal#3]
I am using the latest version of evolution x. It works fine without installing magisk26.3, but after installing it, the phone will always show that the phone is starting and cannot enter the desktop. And btw, I installed it by flashing the boot.img patched by magisk.Now there is some log about this failed:1.[dmesg.txt](https://github.com/weaponmasterjax/device_xiaomi_everpal/files/12884683/dmesg.txt)
2.[logcat.txt](https://github.com/weaponmasterjax/device_xiaomi_everpal/files/12884684/logcat.txt)

**Comment by weaponmasterjax** [comment]
@chen2021-web Wipe dat
