### ISSUE TITLE
Wired headphones questions (audio leaks when screen is locked and turned back on)

### ISSUE THREAD

**Issue by chen2021-web** [weaponmasterjax/device_xiaomi_everpal#4]
Steps to reproduce: 1. Plug in wired headphones
2. Lock screen
3. Reopen the screen
4. You’ll find audio leaks
This is log(through adb logcat):
[log-audio.txt](https://github.com/weaponmasterjax/device_xiaomi_everpal/files/13327573/log-audio.txt)

**Comment by chen2021-web** [comment]
The question is happened by EvolutionX 7.9.9 RC2.

**Comment by chen2021-web** [comment]
This issue occurs in EvolutionX 7.9.9 RC2.

**Comment by weaponmasterjax** [comment]
Thanks for your feedback.
We have examined the log, and there's no useful info on this problem as always😂. And this is a known issue for our device.

**Comment by weaponmasterjax** [comment]
The possible workaround is to try turn off lockscreen sound through some ways.

**Comment by weaponmasterjax** [comment]
Known issue. Will be fixed with new dt.
